# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

dist: trusty
sudo: required

language: python
python:
  - 3.5
  - 3.4
  - 3.6
  - 2.7

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -U tox-travis
    - pip install coveralls

# command to run tests, e.g. python setup.py test
script:
    - tox
    - sonar-scanner

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
    provider: pypi
    distributions: sdist bdist_wheel
    user: fifman
    password:
        secure: PLEASE_REPLACE_ME
    on:
        tags: true
        repo: fifman/tangle
        python: 2.7

addons:
    sonarcloud:
        organization: "fifman-github" # the key of the org you chose at step #3
        token:
            secure: "Ya9eKSe02wHcqOD5n0OJi4qVvEk+XVi3zpYxM+/ihpmoW2k1YKAaAM9f9J99/wwNbeNs8GEbaWuAjZyIDq+MfBf3X6MnP7KuPUoYkvVc8I0MRgjnSjUuAt3VmfrySucwsPg8yoy1U+K6hitf6YaBzJHRht2JUHsNnfCwuz+jPjdDuEKrpgsbmuW5XptS8aCd/CMVzbpxUU9YJ4Nab/XN9I7GfN5f/rJymNA0p75LrMo10JBZjEJb+yEQ2X0fBd+h4jx6Ek1qaFGUhpElAcHeF7btsouz9dvhuxbNOOjsU+F/R/yLfSr4v3Z8R1TJp6B65SOAGjeWeNdfMw8ctOud2xJ/q3HLe5BMUrD15fObCqEeNq29douI/DKiXA1eSTM8l8QcBgKie1i8S1p2BhZVp99nybvAVVP8LiGhSal1Icdq6qNCqUNp26Xe2yWBMarCzvhn5DV22fXA6J4EE7aRY7tJrrot4tmsGw7huCELNPZeQm1j6zqrQNimYtn+6V/TMxFDiUzZ6vb6xu+h7pI8Zy7e2AjfzWNrVzCASAwWtuejve/0Aci4XTvb0EIo85NnD40uIQgx7YRpJxU8bmqs5zz8V2go/sHMZM0fh7YO5ZiQZqDyFxVPfJqTg6R1Ij6qWA0I+qaVkjb4NtWCUpaq5fAdDd5NpcxWCFSB7H0PRVE="
